### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by zryambus** [hippiehunter/GifRenderer#1]
Can you say how to istall your app for solution and be able to use it?

**Comment by madkat** [comment]
You should clone the repository and include the project in your solution. Reference the project where it is needed. To clone, use: git clone https://github.com/hippiehunter/GifRenderer.git

GifRender provides a control that handles all the work. All you need to do is pass it a URL to a gif.

So in the top of the file where you want to use the control, add a namespace like this:

``` xml
    xmlns:gif="using:GifRenderer"
```

Then in the code, do something similar to this: 

``` xml
    <gif:ZoomableImageControl DataContext="{Binding Url}" />
```
