### ISSUE TITLE
Request: MP4 / GIFV support

### ISSUE THREAD

**Issue by LostLogic** [hippiehunter/GifRenderer#3]
Thanks for a fantastic control. It shows any kind of image like it's nobody's business.
A couple of requests:
MP4 and GIFV support, with looping, of course. :)

Double tap to zoom in to next screen fit. IE:
Image is filling width. Double tap -> Image fills to height.

Thanks again for this fantastic control!

**Comment by hippiehunter** [comment]
I'm definitely on-board with the double tap to zoom stuff but MP4 and GIFV would require me to take a dependency on PlayerFramework or something like that and I'm not certain I want to do that. Is there any particular reason you don't just handle those file types with PlayerFramework directly?

**Comment by LostLogic** [comment]
Only for my own convenience. But as you say, I agree it would be better to handle it through that framework than adding the already existing framework with your control.

The zoom would be amazing though :)

**Comment by hippiehunter** [comment]
ok, I've added double tap to zoom. Its not quite what you asked for but your described solution had some edge cases where it wouldnt really do what a user expected. This one is 2 steps of zoom then the 3rd double tap returns to fit (height or width)
